### ISSUE TITLE
Attachments don't honor variable price selections

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-download-email-attachments#1]
If you enable variable pricing, and specific different files for different price IDs, all files for the download are attached.

To replicate, create  variable price product with 2 price IDs, and attach 2 files. Have the first tile be for the first price id, and the 2nd file for the 2nd price id. Purchase the product (either price id), and the email will contain both attachments.

**Comment by SDavisMedia** [comment]
Working for me on `issue/1`. :+1:
